Order and Order Item entities/dto/mapper/repository/service/files were added to application.
oleksandr-chernetskyi/online-book-store_springboot-app pull request #11
Opened 2024-03-12 15:19 UTC by oleksandr-chernetskyi

2024-03-13 10:01 UTC, okuzan requested changes

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/mapper/order/OrderMapper.java
> +    @Mappings({@Mapping(target = "userId", source = "user.id"),
just use @Mapping, without enclosing @mappings

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/model/Order.java
> +@Where(clause = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE orders SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(clause = "is_deleted = FALSE")
```

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/model/OrderItem.java
> +@Where(clause = "is_deleted = false")
same

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/service/impl/OrderServiceImpl.java
> +                });
extract to a separate method, this one is bloated

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/service/impl/OrderServiceImpl.java
> +                    throw new EntityNotFoundException("Can't find order by existing ID");
always include id in such exception messages

2024-03-13 10:01 UTC, okuzan commented on src/main/java/springboot/onlinebookstore/service/impl/OrderServiceImpl.java
> +                    return orderResponseDto;
to a private method

2024-03-13 10:01 UTC, okuzan commented on src/main/resources/db/changelog/changes/22-insert-order-items-into-order-items-table.yaml
> +                  value: "30"
```suggestion
                  value: "30"

```

2024-03-16 16:35 UTC, kerrrusha approved these changes

2024-03-17 15:50 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/service/impl/OrderServiceImpl.java
> +        order.setTotal(BigDecimal.ZERO);
```suggestion
```

2024-03-17 15:50 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/validation/status/Status.java
> +public @interface Status {
delete this annotation.
We should not create unique annotation for each enum in the app

2024-03-19 11:18 UTC, merged