A shopping cart model, controller, repository, and service tiers have…
oleksandr-chernetskyi/online-book-store_springboot-app pull request #9
Opened 2024-02-24 19:27 UTC by oleksandr-chernetskyi

… been implemented. Also, necessary files for the creation of new tables in the db.changelog-master.yaml file have been created.

2024-02-25 12:10 UTC, MentorMA requested changes

2024-02-25 12:10 UTC, MentorMA commented on src/main/java/springboot/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +                    return new NoShoppingCartException("Shopping cart not found for user");
Did you try to throw instead of return?

2024-02-25 17:33 UTC, Rommelua requested changes

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.save(cartItemRequestDto);
```suggestion
        return shoppingCartService.addCartItem(cartItemRequestDto);
```

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto update(@RequestBody @Valid
```suggestion
    public CartItemResponseDto updateCartItem(@RequestBody @Valid
```

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto cartItemResponseDto(@RequestBody @Valid
Think about method name

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto shoppingCartResponseDto() {
Think about method name

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    private final CartItemService cartItemService;
Do not use CartItemService here
```suggestion
```

2024-02-25 17:33 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/service/CartItemService.java
> +    void setCartItemsAndShoppingCart(User user, CartItem cartItem);
```suggestion
```

2024-02-26 10:10 UTC, Rommelua requested changes

2024-02-26 10:10 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/service/CartItemService.java
> +    CartItemResponseDto save(CartItemRequestDto cartItemRequestDto);
I do not see usage of this method

2024-02-26 10:10 UTC, Rommelua commented on src/main/java/springboot/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItemResponseDto.setBookTitle(cartItem.getBook().getTitle());
use mapper for mapping)

2024-02-26 15:19 UTC, Vasul-Pankiv approved these changes

2024-02-26 15:32 UTC, merged